export const base: string;
export const chosenTags: string;
export const form: string;
export const formContainer: string;
export const handles: string;
export const mnContestId: string;
export const problemCard: string;
export const rating: string;
export const tagContainer: string;
